### ISSUE TITLE
py-lmdb compatibility issue

### ISSUE THREAD

**Issue by pgmillon** [kriszyp/lmdb-js#193]
Node v18.9.1
"lmdb": "^2.6.8"
Alpine 3.16.12

Install py-lmdb in addition to node/lmdb-js:
```
# python3 -m ensurepip
# apk add g++ make patch
# python3 -m pip install lmdb
```

main.mjs
```
import { open } from 'lmdb';
let myDB = open({
    path:  'test.mdb',
    maxDbs: 1
});

let db = myDB.openDB('documents', {})
await db.put('key1', 'value1')
```

main.py
```
import lmdb

env = lmdb.open('test.mdb', max_dbs=1, subdir=False)

db = env.open_db('documents'.encode())

with env.begin(write=True) as txn:
    for key, value in txn.cursor(db):
        print(key, value)
```

If DB is created by lmdb-js I have a MDB_VERSION_MISMATCH: Database environment version mismatch on the Python side.
If created by py-lmdb, I have a MDB_INVALID: File is not an LMDB file on the NodeJS side.

Seems both py-lmdb & lmdb-js uses LMDB 0.9.29 as of today.

**Comment by pgmillon** [comment]
Reported on py-lmdb: https://github.com/jnwatson/py-lmdb/issues/329

**Comment by kriszyp** [comment]
@pgmillon lmdb-js actually uses LMDB 0.9.90, which is data version V2, and if py-lmdb uses 0.9.29, which is data version V1. However, I actually have a separate build to build to lmdb-js for 0.9.29/V1 (since it is the "release" version), and I had been meaning to publish with it. So I have run that and published the build to lmdb@v2.6.8-v1. Do you want to try that out and see if it is compatible with py-lmdb?
(eventually would like to publish that to lmdb-v1, but that will take a bit more work)

**Comment by pgmillon** [comment]
@kriszyp thanks for the quick answer and workaround. 
First tests are positive, many thanks.

If I may, I don't think using an unreleased version of LMDB should be part of the mainstream lmbd-js releases; it should be identified correctly, and given the impactful change probably even come as a major bump (e.g. 3.0-beta1).

Thanks for the hard work.

**Comment by kamilchm** [comment]
Hey @kriszyp, I'm using nim wrapper for lmdb which uses version 0.9.29. I've been trying to find the original source for 0.9.90, which you use, so that I can update the nim wrapper, but I've failed.
This may not be a question for you, but it looks like you already know the answer. How do you keep track of new versions of lmdb?

**Comment by kriszyp** [comment]
I pull the LMDB source from:
https://git.openldap.org/openldap/openldap/-/tree/mdb.master3/libraries/liblmdb
(you can check the version here:
https://git.openldap.org/openldap/openldap/-/blob/mdb.master3/libraries/liblmdb/lmdb.h#L237)
The commit rate isn't very high, so it is easy enough to just occasionally update from that branch.

**Comment by kamilchm** [comment]
I've seen this branch before, but I thought it was a temporary leftover and didn't look into it 🙃.
Thanks Kris, and thanks for maintaining this cool library!
